CREATE TABLE `MATERIAL_PROD` (
  `PRODMAT_ID` int NOT NULL AUTO_INCREMENT,
  `MAT_NR` varchar(10) DEFAULT NULL,
  `TYP` varchar(2) DEFAULT NULL,
  `QTY` int DEFAULT NULL,
  `DELTA_E` float DEFAULT NULL,
  `PPML` int DEFAULT NULL,
  `WHITNESS` int DEFAULT NULL,
  `VISCOSITY` float DEFAULT NULL,
  `ABSORBENCY` float DEFAULT NULL,
  `CHARG_NR` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`PRODMAT_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci